### ISSUE TITLE
httprobe installation

### ISSUE THREAD

**Issue by DenizParlak** [cihanmehmet/sub.sh#3]
"/usr/share/bin" path not correct to copy the executable file.

Right steps should be like this:

wget https://github.com/tomnomnom/httprobe/releases/download/v0.1.2/httprobe-linux-amd64-0.1.2.tgz

tar -xvzf httprobe-linux-amd64-0.1.2.tgz

cp httprobe /usr/local/bin

chmod +x /usr/local/bin/httprobe

**Comment by cihanmehmet** [comment]
Thank you for the information. I've edited README.md
