### ISSUE TITLE
Sub.sh returning 0 results with particular domains

### ISSUE THREAD

**Issue by sw33tLie** [cihanmehmet/sub.sh#5]
Hello, there's a problem with domains like bingo.com.
The script runs and it always ends up with 0 results.
I believe it's caused by the -- present in some cert.sh subdomains (like autodiscover.costa--bingo.com) but i'm not sure.
If someone could check it out that would be awesome!

**Comment by cihanmehmet** [comment]
I tried, it did not. Found sub.sh domain.Can you check back?
<img width="487" alt="bingo" src="https://user-images.githubusercontent.com/7144304/76146108-372e3e00-60a1-11ea-8a3c-c5b22528fade.png">
